exports.introsData=[
    {
        "id": 223835009,
        "node_id": "MDEwOlJlcG9zaXRvcnkyMjM4MzUwMDk=",
        "name": "CT_OBJ",
        "full_name": "Intern2020OJT/CT_OBJ",
        "private": false,
        "owner": {
            "login": "Intern2020OJT",
            "id": 56333136,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjU2MzMzMTM2",
            "avatar_url": "https://avatars0.githubusercontent.com/u/56333136?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Intern2020OJT",
            "html_url": "https://github.com/Intern2020OJT",
            "followers_url": "https://api.github.com/users/Intern2020OJT/followers",
            "following_url": "https://api.github.com/users/Intern2020OJT/following{/other_user}",
            "gists_url": "https://api.github.com/users/Intern2020OJT/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Intern2020OJT/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Intern2020OJT/subscriptions",
            "organizations_url": "https://api.github.com/users/Intern2020OJT/orgs",
            "repos_url": "https://api.github.com/users/Intern2020OJT/repos",
            "events_url": "https://api.github.com/users/Intern2020OJT/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Intern2020OJT/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ",
        "description": "github issues analytics",
        "fork": false,
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "forks_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/forks",
        "keys_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/teams",
        "hooks_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/hooks",
        "issue_events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/events",
        "assignees_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/tags",
        "blobs_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/languages",
        "stargazers_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/stargazers",
        "contributors_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/contributors",
        "subscribers_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/subscribers",
        "subscription_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/subscription",
        "commits_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/merges",
        "archive_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/downloads",
        "issues_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels{/name}",
        "releases_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/deployments",
        "created_at": "2019-11-25T01:05:38Z",
        "updated_at": "2019-12-11T01:28:33Z",
        "pushed_at": "2019-12-16T01:42:14Z",
        "git_url": "git://github.com/Intern2020OJT/CT_OBJ.git",
        "ssh_url": "git@github.com:Intern2020OJT/CT_OBJ.git",
        "clone_url": "https://github.com/Intern2020OJT/CT_OBJ.git",
        "svn_url": "https://github.com/Intern2020OJT/CT_OBJ",
        "homepage": "https://intern2020ojt.github.io/CT_OBJ/",
        "size": 1811,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": true,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 19,
        "license": null,
        "forks": 0,
        "open_issues": 19,
        "watchers": 0,
        "default_branch": "master",
        "temp_clone_token": null,
        "organization": {
            "login": "Intern2020OJT",
            "id": 56333136,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjU2MzMzMTM2",
            "avatar_url": "https://avatars0.githubusercontent.com/u/56333136?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Intern2020OJT",
            "html_url": "https://github.com/Intern2020OJT",
            "followers_url": "https://api.github.com/users/Intern2020OJT/followers",
            "following_url": "https://api.github.com/users/Intern2020OJT/following{/other_user}",
            "gists_url": "https://api.github.com/users/Intern2020OJT/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Intern2020OJT/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Intern2020OJT/subscriptions",
            "organizations_url": "https://api.github.com/users/Intern2020OJT/orgs",
            "repos_url": "https://api.github.com/users/Intern2020OJT/repos",
            "events_url": "https://api.github.com/users/Intern2020OJT/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Intern2020OJT/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "network_count": 0,
        "subscribers_count": 3,
        "issues":[
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/69",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/69/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/69/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/69/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/pull/69",
                "id": 538141619,
                "node_id": "MDExOlB1bGxSZXF1ZXN0MzUzMzQwNzYz",
                "number": 69,
                "title": "Server/develop",
                "user": {
                    "login": "AyaseEUmi",
                    "id": 49441287,
                    "node_id": "MDQ6VXNlcjQ5NDQxMjg3",
                    "avatar_url": "https://avatars2.githubusercontent.com/u/49441287?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/AyaseEUmi",
                    "html_url": "https://github.com/AyaseEUmi",
                    "followers_url": "https://api.github.com/users/AyaseEUmi/followers",
                    "following_url": "https://api.github.com/users/AyaseEUmi/following{/other_user}",
                    "gists_url": "https://api.github.com/users/AyaseEUmi/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/AyaseEUmi/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/AyaseEUmi/subscriptions",
                    "organizations_url": "https://api.github.com/users/AyaseEUmi/orgs",
                    "repos_url": "https://api.github.com/users/AyaseEUmi/repos",
                    "events_url": "https://api.github.com/users/AyaseEUmi/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/AyaseEUmi/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2019-12-16T01:37:38Z",
                "updated_at": "2019-12-16T01:42:13Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "pull_request": {
                    "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/pulls/69",
                    "html_url": "https://github.com/Intern2020OJT/CT_OBJ/pull/69",
                    "diff_url": "https://github.com/Intern2020OJT/CT_OBJ/pull/69.diff",
                    "patch_url": "https://github.com/Intern2020OJT/CT_OBJ/pull/69.patch"
                },
                "body": ""
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/49",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/49/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/49/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/49/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/49",
                "id": 536164230,
                "node_id": "MDU6SXNzdWU1MzYxNjQyMzA=",
                "number": 49,
                "title": "???????",
                "user": {
                    "login": "airoucat",
                    "id": 28886702,
                    "node_id": "MDQ6VXNlcjI4ODg2NzAy",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/28886702?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/airoucat",
                    "html_url": "https://github.com/airoucat",
                    "followers_url": "https://api.github.com/users/airoucat/followers",
                    "following_url": "https://api.github.com/users/airoucat/following{/other_user}",
                    "gists_url": "https://api.github.com/users/airoucat/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/airoucat/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/airoucat/subscriptions",
                    "organizations_url": "https://api.github.com/users/airoucat/orgs",
                    "repos_url": "https://api.github.com/users/airoucat/repos",
                    "events_url": "https://api.github.com/users/airoucat/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/airoucat/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2019-12-11T06:10:50Z",
                "updated_at": "2019-12-12T07:49:04Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "```\r\n{\r\n    \"name\": //???\r\n    \"labels\":{\r\n                \"name\":\r\n                \"name\":\r\n                ...\r\n             }//??????label\r\n    \"issues\":{\r\n                \"title\":\r\n                \"html_url\":\r\n                \"labels\"://??issues??label\r\n                \"state\":\r\n                \"assignees\":\r\n                \"comments\":\r\n                \"created_at\":\r\n                \"closed_at\":null\r\n             }\r\n     \"languages\":\r\n}\r\n```"
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/43",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/43/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/43/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/43/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/43",
                "id": 536098033,
                "node_id": "MDU6SXNzdWU1MzYwOTgwMzM=",
                "number": 43,
                "title": "????????",
                "user": {
                    "login": "Shanxiaolin",
                    "id": 55526635,
                    "node_id": "MDQ6VXNlcjU1NTI2NjM1",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/55526635?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Shanxiaolin",
                    "html_url": "https://github.com/Shanxiaolin",
                    "followers_url": "https://api.github.com/users/Shanxiaolin/followers",
                    "following_url": "https://api.github.com/users/Shanxiaolin/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Shanxiaolin/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Shanxiaolin/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Shanxiaolin/subscriptions",
                    "organizations_url": "https://api.github.com/users/Shanxiaolin/orgs",
                    "repos_url": "https://api.github.com/users/Shanxiaolin/repos",
                    "events_url": "https://api.github.com/users/Shanxiaolin/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Shanxiaolin/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486730,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                        "name": "?????or????",
                        "color": "fce325",
                        "default": false,
                        "description": ""
                    },
                    {
                        "id": 1704491139,
                        "node_id": "MDU6TGFiZWwxNzA0NDkxMTM5",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9AAPI",
                        "name": "???API",
                        "color": "414fbf",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2019-12-11T02:09:02Z",
                "updated_at": "2019-12-11T07:07:20Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "### ??????\r\n- user.js  ????\r\n- import_uesr.js  ?????\r\n- mod_user.js ?????????????????\r\n![image](https://user-images.githubusercontent.com/55526635/70584647-c770fa00-1bfc-11ea-999d-86fb62e1c776.png)\r\n`const ModelTest = new Model(DB_NAME_ISSUE, SCHEMA_SXL, Test)`\r\n- DB_NAME_ISSUE???db.js???????????????????????????\r\n### ????????????\r\ntest.js\r\n```\r\nexports.test = [\r\n    { genre: 'Sports', sold: 8 },  \r\n    { genre: 'Action', sold: 9},\r\n    { genre: 'Shooter', sold: 6 },\r\n    { genre: 'Strategy', sold: 8},\r\n    { genre: 'Other', sold: 7}\r\n  ]  \r\n```\r\nimport_test.js\r\n```\r\nconst { test }           = require(\"./test\");\r\nconst ModelTest       = require(\"../modules/system/models/mod_test\");\r\n\r\nconst importTest = async () => {\r\n  try {\r\n    await Promise.all(test.map(async (record) => {\r\n      await ModelTest.create({...record});\r\n    }));\r\n  } catch (err) {\r\n    throw err;\r\n  }\r\n};\r\n\r\nimportTest().then(() => {\r\n  console.log('ok');\r\n  process.exit();\r\n}).catch((err) => {\r\n  console.log('error');\r\n  console.log(err);\r\n  process.exit();\r\n});\r\n```\r\nmod_test.js\r\n```\r\nconst SchemaCommon    = require(\"../../mod_base\");\r\nconst mongoose   = require(\"mongoose\");\r\nconst Model           = require(\"../../../core/model\");\r\nconst constant        = require(\"../../../core/constant\");\r\nconst { Schema } = mongoose;\r\nconst { Mixed }   = Schema.Types;\r\nconst { DB_NAME_ISSUE, SCHEMA_SXL } = constant;\r\n\r\nconst { BaseSchema } = SchemaCommon;\r\n\r\nconst Test = new BaseSchema({\r\n  genre:              { type: String, description: \"???\" },\r\n  sold:               { type: Mixed, description: \"???\" },  \r\n});\r\n\r\nconst ModelTest = new Model(DB_NAME_ISSUE, SCHEMA_SXL, Test);\r\n\r\nmodule.exports = ModelTest;\r\n\r\n```\r\n- import_test.js????ctrl_  ??????????\r\n \r\n"
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/41",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/41/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/41/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/41/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/41",
                "id": 536084919,
                "node_id": "MDU6SXNzdWU1MzYwODQ5MTk=",
                "number": 41,
                "title": "???GET????????????",
                "user": {
                    "login": "Progyang",
                    "id": 50037121,
                    "node_id": "MDQ6VXNlcjUwMDM3MTIx",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/50037121?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Progyang",
                    "html_url": "https://github.com/Progyang",
                    "followers_url": "https://api.github.com/users/Progyang/followers",
                    "following_url": "https://api.github.com/users/Progyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Progyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Progyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Progyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/Progyang/orgs",
                    "repos_url": "https://api.github.com/users/Progyang/repos",
                    "events_url": "https://api.github.com/users/Progyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Progyang/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486730,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                        "name": "?????or????",
                        "color": "fce325",
                        "default": false,
                        "description": ""
                    },
                    {
                        "id": 1704491139,
                        "node_id": "MDU6TGFiZWwxNzA0NDkxMTM5",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9AAPI",
                        "name": "???API",
                        "color": "414fbf",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2019-12-11T01:18:32Z",
                "updated_at": "2019-12-11T01:18:32Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "#### ???\r\n![image](https://user-images.githubusercontent.com/50037121/70582884-fab08a80-1bf6-11ea-87f6-818b0e6b96be.png)\r\n#### ???\r\n![image](https://user-images.githubusercontent.com/50037121/70582944-2fbcdd00-1bf7-11ea-8d0b-772c41ec90be.png)\r\n"
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/34",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/34/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/34/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/34/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/34",
                "id": 535498202,
                "node_id": "MDU6SXNzdWU1MzU0OTgyMDI=",
                "number": 34,
                "title": "????????",
                "user": {
                    "login": "Shanxiaolin",
                    "id": 55526635,
                    "node_id": "MDQ6VXNlcjU1NTI2NjM1",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/55526635?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Shanxiaolin",
                    "html_url": "https://github.com/Shanxiaolin",
                    "followers_url": "https://api.github.com/users/Shanxiaolin/followers",
                    "following_url": "https://api.github.com/users/Shanxiaolin/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Shanxiaolin/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Shanxiaolin/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Shanxiaolin/subscriptions",
                    "organizations_url": "https://api.github.com/users/Shanxiaolin/orgs",
                    "repos_url": "https://api.github.com/users/Shanxiaolin/repos",
                    "events_url": "https://api.github.com/users/Shanxiaolin/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Shanxiaolin/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486730,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                        "name": "?????or????",
                        "color": "fce325",
                        "default": false,
                        "description": ""
                    },
                    {
                        "id": 1704491139,
                        "node_id": "MDU6TGFiZWwxNzA0NDkxMTM5",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9AAPI",
                        "name": "???API",
                        "color": "414fbf",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 3,
                "created_at": "2019-12-10T05:12:12Z",
                "updated_at": "2019-12-11T07:31:15Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "### ????\r\n- index.js??api   ??ctrlUser.simpleLogin??  \r\n- ctr_user   ??\r\n- ModelUser (mod_user.js) ??\r\n- Model (model.js) ??\r\n- db.js \r\n### ????\r\n- index.js ????post????????ctr_user???\r\n  `const { name, pass } = req.body`\r\n- ??????????get?api??????????????????\r\n- ModelUser?????model??????????????mongodb??????\r\n???model.js\r\n- ????model.js?????????????????\r\n```\r\nconstructor(code, name, scheme) {\r\n    const conn = db.createConnection(code);\r\n    this.m = conn.model(name, scheme);//??????\r\n    //this.m ?????? Model { User } Model { Token }????????????????????\r\n```\r\n- ???????????????????model.js??????model.js???????????mongodb??????\r\n### ??????????get??????\r\nctrl_modul.js\r\n```\r\nconst log         = require(\"../../../core/logger\");\r\nconst ModelUser    = require(\"../models/mod_user\");\r\nexports.modul = async (req) => {\r\n  log.info(\"user.modul() start.\");\r\n  try {\r\n    log.info(\"ctr_modul 1\")\r\n    const id = '5de73eba2875ec1c9cb61997';\r\n    log.info(\"ctr_modul 2\")\r\n    const projection = \"\";\r\n    log.info(\"ctr_modul 3\")\r\n    const message = await ModelUser.get(id, projection);\r\n    log.info(\"ctr_modul 4\")\r\n    return message;\r\n  } catch (err) {\r\n    log.info(\"user.modul() error.\");\r\n    log.error(err);\r\n    throw err;\r\n  }\r\n};\r\n ```\r\nindex.js?api\r\n```\r\napp.get(`/${appName}/openingissues`, async (req,res) => {\r\n    try {\r\n      const result = await ctrlModul.modul(req);\r\n      response.sendSuccess(res, result);\r\n    } catch (err) {\r\n      response.sendError(res,err);\r\n    }\r\n  }); \r\n```\r\n\r\n"
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/28",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/28/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/28/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/28/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/28",
                "id": 534678526,
                "node_id": "MDU6SXNzdWU1MzQ2Nzg1MjY=",
                "number": 28,
                "title": "Tooltip????????",
                "user": {
                    "login": "Progyang",
                    "id": 50037121,
                    "node_id": "MDQ6VXNlcjUwMDM3MTIx",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/50037121?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Progyang",
                    "html_url": "https://github.com/Progyang",
                    "followers_url": "https://api.github.com/users/Progyang/followers",
                    "following_url": "https://api.github.com/users/Progyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Progyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Progyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Progyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/Progyang/orgs",
                    "repos_url": "https://api.github.com/users/Progyang/repos",
                    "events_url": "https://api.github.com/users/Progyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Progyang/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486730,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                        "name": "?????or????",
                        "color": "fce325",
                        "default": false,
                        "description": ""
                    },
                    {
                        "id": 1704490958,
                        "node_id": "MDU6TGFiZWwxNzA0NDkwOTU4",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9A%E5%89%8D%E7%AB%AF",
                        "name": "?????",
                        "color": "e99695",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2019-12-09T04:12:07Z",
                "updated_at": "2019-12-09T04:12:24Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "[??API??](https://bizcharts.net/products/bizCharts/api/graphic)\r\n```\r\n                <Geom\r\n                   type=\"interval\"\r\n                    position=\"shortName*comments\"\r\n                    tooltip={['fullName*comments', (fullName, comments) => {\r\n                        return {\r\n                          //??? tooltip ???? title ??????\r\n                          name: fullName,\r\n                          title: fullName,\r\n                          value: comments\r\n                        };\r\n                      }]}>\r\n                    <Label content={['comments']} />{' '}\r\n                </Geom> \r\n```\r\n**?Geom(????)?????tooltip????**\r\n![image](https://user-images.githubusercontent.com/50037121/70406811-e0eb3800-1a7c-11ea-8cc7-1cf4784bc94e.png)\r\n???????????\r\n![image](https://user-images.githubusercontent.com/50037121/70406868-13953080-1a7d-11ea-9400-dd482110f6c9.png)\r\n\r\n\r\n"
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/24",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/24/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/24/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/24/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/24",
                "id": 533825556,
                "node_id": "MDU6SXNzdWU1MzM4MjU1NTY=",
                "number": 24,
                "title": "UI??????????????",
                "user": {
                    "login": "AyaseEUmi",
                    "id": 49441287,
                    "node_id": "MDQ6VXNlcjQ5NDQxMjg3",
                    "avatar_url": "https://avatars2.githubusercontent.com/u/49441287?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/AyaseEUmi",
                    "html_url": "https://github.com/AyaseEUmi",
                    "followers_url": "https://api.github.com/users/AyaseEUmi/followers",
                    "following_url": "https://api.github.com/users/AyaseEUmi/following{/other_user}",
                    "gists_url": "https://api.github.com/users/AyaseEUmi/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/AyaseEUmi/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/AyaseEUmi/subscriptions",
                    "organizations_url": "https://api.github.com/users/AyaseEUmi/orgs",
                    "repos_url": "https://api.github.com/users/AyaseEUmi/repos",
                    "events_url": "https://api.github.com/users/AyaseEUmi/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/AyaseEUmi/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704489925,
                        "node_id": "MDU6TGFiZWwxNzA0NDg5OTI1",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E4%BC%98%E5%85%88%E5%BA%A6%EF%BC%9A%E4%B8%AD",
                        "name": "?????",
                        "color": "56d371",
                        "default": false,
                        "description": ""
                    },
                    {
                        "id": 1704486730,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                        "name": "?????or????",
                        "color": "fce325",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2019-12-06T08:47:47Z",
                "updated_at": "2019-12-09T04:06:21Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": ""
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/12",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/12/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/12/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/12/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/12",
                "id": 532466157,
                "node_id": "MDU6SXNzdWU1MzI0NjYxNTc=",
                "number": 12,
                "title": "Card?????",
                "user": {
                    "login": "Progyang",
                    "id": 50037121,
                    "node_id": "MDQ6VXNlcjUwMDM3MTIx",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/50037121?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Progyang",
                    "html_url": "https://github.com/Progyang",
                    "followers_url": "https://api.github.com/users/Progyang/followers",
                    "following_url": "https://api.github.com/users/Progyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Progyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Progyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Progyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/Progyang/orgs",
                    "repos_url": "https://api.github.com/users/Progyang/repos",
                    "events_url": "https://api.github.com/users/Progyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Progyang/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486730,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                        "name": "?????or????",
                        "color": "fce325",
                        "default": false,
                        "description": ""
                    },
                    {
                        "id": 1704490958,
                        "node_id": "MDU6TGFiZWwxNzA0NDkwOTU4",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9A%E5%89%8D%E7%AB%AF",
                        "name": "?????",
                        "color": "e99695",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2019-12-04T05:51:55Z",
                "updated_at": "2019-12-04T05:54:46Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "```\r\nimport React, { useState } from 'react';\r\nimport { Card } from 'antd';\r\n\r\nimport SClassifyLablesAnalyseBar from './SClassifyLablesAnalyseBar';\r\nimport SClassifyLablesAnalysePie from './SClassifyLablesAnalysePie';\r\n\r\nconst SClassifyLablesAnalyse = () => {\r\n  const [tabs, setState] = useState('bar');\r\n  \r\n  const tabList = [\r\n    {\r\n      key: 'bar',\r\n      tab: '???',\r\n    },\r\n    {\r\n      key: 'pie',\r\n      tab: '???',\r\n    },\r\n  ];\r\n  \r\n  const contentList = {\r\n    bar: <SClassifyLablesAnalyseBar />,\r\n    pie: <SClassifyLablesAnalysePie />,\r\n  };\r\n\r\n  return (\r\n    <Card\r\n      style={{ width: '600px', height: '500px' }}\r\n      title=\"Lables??\"\r\n      tabList={tabList}\r\n      activeTabKey={tabs}\r\n      onTabChange={key => {\r\n        setState(key);\r\n      }}\r\n    >\r\n      {contentList[tabs]}\r\n    </Card>\r\n  );\r\n};\r\n\r\nexport default SClassifyLablesAnalyse;\r\n```\r\ncontentList ???????????,???????tab,???????tab??????,??????????????\r\n![image](https://user-images.githubusercontent.com/50037121/70116403-9729d880-169d-11ea-8dd6-4e834970eaf7.png)\r\n![image](https://user-images.githubusercontent.com/50037121/70116409-9ee97d00-169d-11ea-9f76-04e3d6610c27.png)\r\n\r\n"
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/11",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/11/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/11/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/11/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/11",
                "id": 532465568,
                "node_id": "MDU6SXNzdWU1MzI0NjU1Njg=",
                "number": 11,
                "title": "??DOM??????",
                "user": {
                    "login": "Progyang",
                    "id": 50037121,
                    "node_id": "MDQ6VXNlcjUwMDM3MTIx",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/50037121?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Progyang",
                    "html_url": "https://github.com/Progyang",
                    "followers_url": "https://api.github.com/users/Progyang/followers",
                    "following_url": "https://api.github.com/users/Progyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Progyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Progyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Progyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/Progyang/orgs",
                    "repos_url": "https://api.github.com/users/Progyang/repos",
                    "events_url": "https://api.github.com/users/Progyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Progyang/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486730,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                        "name": "?????or????",
                        "color": "fce325",
                        "default": false,
                        "description": ""
                    },
                    {
                        "id": 1704490958,
                        "node_id": "MDU6TGFiZWwxNzA0NDkwOTU4",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9A%E5%89%8D%E7%AB%AF",
                        "name": "?????",
                        "color": "e99695",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2019-12-04T05:49:55Z",
                "updated_at": "2019-12-05T00:46:55Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "![image](https://user-images.githubusercontent.com/50037121/70115998-69905f80-169c-11ea-8ba5-e554d855434c.png)\r\n??,????SClassifyAnalyse??,???<SClassifyLablesAnalyse /><SClassifyAssigneesAnalyse />??????????????\r\n![image](https://user-images.githubusercontent.com/50037121/70116094-ad836480-169c-11ea-9537-157653e9ac82.png)\r\n????????,??<SClassifyAnalyse />????????\r\n![image](https://user-images.githubusercontent.com/50037121/70116136-c7bd4280-169c-11ea-869a-4f22dec3c9f7.png)\r\n????SHome?,???app.jsx????\r\n"
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/10",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/10/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/10/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/10/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/10",
                "id": 532399053,
                "node_id": "MDU6SXNzdWU1MzIzOTkwNTM=",
                "number": 10,
                "title": "?????????API",
                "user": {
                    "login": "Shanxiaolin",
                    "id": 55526635,
                    "node_id": "MDQ6VXNlcjU1NTI2NjM1",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/55526635?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Shanxiaolin",
                    "html_url": "https://github.com/Shanxiaolin",
                    "followers_url": "https://api.github.com/users/Shanxiaolin/followers",
                    "following_url": "https://api.github.com/users/Shanxiaolin/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Shanxiaolin/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Shanxiaolin/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Shanxiaolin/subscriptions",
                    "organizations_url": "https://api.github.com/users/Shanxiaolin/orgs",
                    "repos_url": "https://api.github.com/users/Shanxiaolin/repos",
                    "events_url": "https://api.github.com/users/Shanxiaolin/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Shanxiaolin/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486730,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                        "name": "?????or????",
                        "color": "fce325",
                        "default": false,
                        "description": ""
                    },
                    {
                        "id": 1704491139,
                        "node_id": "MDU6TGFiZWwxNzA0NDkxMTM5",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9AAPI",
                        "name": "???API",
                        "color": "414fbf",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2019-12-04T02:05:26Z",
                "updated_at": "2019-12-05T01:41:41Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "### ???????????\r\n- app.js???restAPI???????node.js???????????????????????[Node.js RESTful API](https://www.runoob.com/nodejs/nodejs-restful-api.html)???????npm run start???????????node...?????????node app.js???\r\n### ??????????\r\n- ?src->routes->index.js???API\r\n- ?src->modules->system->controllers?????js?????????????????????\r\n- ctrl_user.js\r\n```\r\nexports.openingissues = async (req) => {\r\n  log.info(\"get openingissues\");\r\n  try{\r\n      res = 2;\r\n      return (res);\r\n    }\r\n  catch(err){\r\n    log.info(\"get openingissues err\")\r\n    log.err(err)\r\n    throw err\r\n  }\r\n}\r\n```\r\n- index.js\r\n```\r\napp.get(`/${appName}/openingissues`, async (req,res) => {\r\n    try {\r\n      // console.log(1)\r\n      const result = await ctrlUser.openingissues(req);\r\n      response.sendSuccess(res, result);\r\n    } catch (err) {\r\n      response.sendError(res,err);\r\n    }\r\n  });\r\n```\r\n???npm run start\r\npostman ??\r\nhttp://localhost:3000/issues/openingissues\r\n???????config->app.js\r\n${appName}???config->app.js   name: \"issues\",  ? ${appName}=issues"
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/9",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/9/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/9/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/9/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/9",
                "id": 532386643,
                "node_id": "MDU6SXNzdWU1MzIzODY2NDM=",
                "number": 9,
                "title": "???????????????????????",
                "user": {
                    "login": "Shanxiaolin",
                    "id": 55526635,
                    "node_id": "MDQ6VXNlcjU1NTI2NjM1",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/55526635?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Shanxiaolin",
                    "html_url": "https://github.com/Shanxiaolin",
                    "followers_url": "https://api.github.com/users/Shanxiaolin/followers",
                    "following_url": "https://api.github.com/users/Shanxiaolin/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Shanxiaolin/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Shanxiaolin/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Shanxiaolin/subscriptions",
                    "organizations_url": "https://api.github.com/users/Shanxiaolin/orgs",
                    "repos_url": "https://api.github.com/users/Shanxiaolin/repos",
                    "events_url": "https://api.github.com/users/Shanxiaolin/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Shanxiaolin/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486730,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                        "name": "?????or????",
                        "color": "fce325",
                        "default": false,
                        "description": ""
                    },
                    {
                        "id": 1704490958,
                        "node_id": "MDU6TGFiZWwxNzA0NDkwOTU4",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9A%E5%89%8D%E7%AB%AF",
                        "name": "?????",
                        "color": "e99695",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2019-12-04T01:41:59Z",
                "updated_at": "2019-12-04T01:42:48Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "### ??????\r\n- ????src->modules->system->scenes?????? jsx ???????Shome.jsx?\r\n- ????src->utils->constants.js ??????????????????????\r\n- ????app.jsx?????????????Stest\r\n`import STest from './modules/system/scenes/STest';`\r\n- ????app.jsx????hook??????????????component={STest}  ;\r\n```\r\n const App = () => {\r\n  return (\r\n    <IntlProvider locale={navigator.language} messages={chooseLocale()}>\r\n      <Router basename={process.env.PUBLIC_URL}>\r\n        { <Switch>\r\n          <PublicRoute path=\"/\" exact component={SLogin} />\r\n          <PublicRoute path={ROUTE_LOGIN} component={SLogin} />\r\n          <PrivateRoute path={ROUTE_TEST} component={STest} />\r\n          <PrivateRoute path={ROUTE_HOME} component={SHome} />\r\n          <Route path={ROUTE_ERROR} exact component={SInternalServerError} />\r\n          <Route path=\"*\" component={SNotFound} />\r\n        </Switch> }\r\n      </Router>\r\n    </IntlProvider>\r\n  );\r\n};\r\n```\r\n`<PrivateRoute><PublicRoute>`?????????????????????\r\n```\r\nconst PrivateRoute = ({ component: Component, ...rest }) => {\r\n  return (\r\n    <Route\r\n      {...rest}\r\n      render={props =>\r\n        storage.isAuthenticatedUser() ? (\r\n          <CDefaultLayout>\r\n            <Component {...props} />\r\n          </CDefaultLayout>\r\n        ) : (\r\n          <Redirect to={ROUTE_LOGIN} />\r\n        )\r\n      }\r\n    />\r\n  );\r\n};\r\n```\r\n????????????????login???????????CDefaultLayout???????????????????????test,home???test??????login??????????test???????login???\r\n????????\r\n\r\n"
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/8",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/8/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/8/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/8/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/8",
                "id": 531675281,
                "node_id": "MDU6SXNzdWU1MzE2NzUyODE=",
                "number": 8,
                "title": "????????Module not found: Can't resolve '@antv/data-set' in 'C:\\Users\\sxl\\CT_Client\\src\\modules\\system\\scenes'",
                "user": {
                    "login": "Shanxiaolin",
                    "id": 55526635,
                    "node_id": "MDQ6VXNlcjU1NTI2NjM1",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/55526635?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Shanxiaolin",
                    "html_url": "https://github.com/Shanxiaolin",
                    "followers_url": "https://api.github.com/users/Shanxiaolin/followers",
                    "following_url": "https://api.github.com/users/Shanxiaolin/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Shanxiaolin/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Shanxiaolin/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Shanxiaolin/subscriptions",
                    "organizations_url": "https://api.github.com/users/Shanxiaolin/orgs",
                    "repos_url": "https://api.github.com/users/Shanxiaolin/repos",
                    "events_url": "https://api.github.com/users/Shanxiaolin/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Shanxiaolin/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486730,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                        "name": "?????or????",
                        "color": "fce325",
                        "default": false,
                        "description": ""
                    },
                    {
                        "id": 1704489186,
                        "node_id": "MDU6TGFiZWwxNzA0NDg5MTg2",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E7%8A%B6%E6%80%81%EF%BC%9ADone",
                        "name": "???Done",
                        "color": "577507",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2019-12-03T02:46:07Z",
                "updated_at": "2019-12-03T02:46:07Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "??????Module??\r\n`npm install ??????????`"
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/7",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/7/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/7/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/7/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/7",
                "id": 530867782,
                "node_id": "MDU6SXNzdWU1MzA4Njc3ODI=",
                "number": 7,
                "title": "???????????",
                "user": {
                    "login": "Progyang",
                    "id": 50037121,
                    "node_id": "MDQ6VXNlcjUwMDM3MTIx",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/50037121?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Progyang",
                    "html_url": "https://github.com/Progyang",
                    "followers_url": "https://api.github.com/users/Progyang/followers",
                    "following_url": "https://api.github.com/users/Progyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Progyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Progyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Progyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/Progyang/orgs",
                    "repos_url": "https://api.github.com/users/Progyang/repos",
                    "events_url": "https://api.github.com/users/Progyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Progyang/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486567,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NTY3",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
                        "name": "?????",
                        "color": "c5def5",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2019-12-02T03:35:46Z",
                "updated_at": "2019-12-02T03:35:46Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "?????????REACT_APP_API_URL,?? http://localhost:3000/issues ??\r\n ![image](https://user-images.githubusercontent.com/50037121/69928776-aa9b3f00-14f7-11ea-91b3-757d9f637a1c.png)\r\n"
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/6",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/6/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/6/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/6/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/6",
                "id": 530155059,
                "node_id": "MDU6SXNzdWU1MzAxNTUwNTk=",
                "number": 6,
                "title": "????",
                "user": {
                    "login": "slsay",
                    "id": 4725762,
                    "node_id": "MDQ6VXNlcjQ3MjU3NjI=",
                    "avatar_url": "https://avatars1.githubusercontent.com/u/4725762?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/slsay",
                    "html_url": "https://github.com/slsay",
                    "followers_url": "https://api.github.com/users/slsay/followers",
                    "following_url": "https://api.github.com/users/slsay/following{/other_user}",
                    "gists_url": "https://api.github.com/users/slsay/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/slsay/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/slsay/subscriptions",
                    "organizations_url": "https://api.github.com/users/slsay/orgs",
                    "repos_url": "https://api.github.com/users/slsay/repos",
                    "events_url": "https://api.github.com/users/slsay/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/slsay/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486567,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NTY3",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
                        "name": "?????",
                        "color": "c5def5",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2019-11-29T04:53:08Z",
                "updated_at": "2019-11-29T04:53:46Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "## ??\r\n* ??git\r\n* ??nvm\r\nhttps://github.com/nvm-sh/nvm\r\n\r\n* ??nvm??node 12.x\r\n```sh\r\n  nvm install 12\r\n```\r\n* ??mongodb???\r\n```sh\r\n$ tar -zxvf mongodb-macos-x86_64-4.2.1.tgz\r\n$ mv mongodb-macos-x86_64-4.2.1.tgz  mongodb-4.2.1\r\n$ cd mongodb-4.2.1\r\n$ mkdir data\r\n$ cd ..\r\n$ bin/mongod --dbpath ./data/\r\n// ????27017\r\n```\r\n### ????\r\n```sh\r\n// ??\r\n$ git clone https://userId:password@github.com/Intern2020OJT/CT_OBJ.git client_dev\r\n$ cd client_dev\r\n$ git checkout client/develop\r\n\r\n// API\r\n$ git clone https://userId:password@github.com/Intern2020OJT/CT_OBJ.git server_dev\r\n$ cd server_dev\r\n$ git checkout server/develop\r\n```\r\n\r\n## API\r\n###  ??\r\n```sh\r\n$ cd server_dev\r\n$ nvm use 12\r\n$ npm install\r\n$ npm run start\r\n```\r\n\r\n##  ??????\r\n```sh\r\n$ cd server_dev\r\n$ nvm use 12\r\n$ node ./src/tool/import_user.js\r\n```\r\n\r\n## ??\r\n### ??\r\n```sh\r\n$ cd client_dev\r\n$ nvm use 12\r\n$ npm install\r\n$ npm run start\r\n```\r\n### ??\r\nhttp://localhost:5000\r\n\r\n![????????? 0031-11-29 12 52 16](https://user-images.githubusercontent.com/4725762/69844424-26eb1380-12a7-11ea-92d7-21205c1c66e2.png)\r\n"
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/5",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/5/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/5/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/5/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/5",
                "id": 530152097,
                "node_id": "MDU6SXNzdWU1MzAxNTIwOTc=",
                "number": 5,
                "title": "??",
                "user": {
                    "login": "slsay",
                    "id": 4725762,
                    "node_id": "MDQ6VXNlcjQ3MjU3NjI=",
                    "avatar_url": "https://avatars1.githubusercontent.com/u/4725762?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/slsay",
                    "html_url": "https://github.com/slsay",
                    "followers_url": "https://api.github.com/users/slsay/followers",
                    "following_url": "https://api.github.com/users/slsay/following{/other_user}",
                    "gists_url": "https://api.github.com/users/slsay/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/slsay/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/slsay/subscriptions",
                    "organizations_url": "https://api.github.com/users/slsay/orgs",
                    "repos_url": "https://api.github.com/users/slsay/repos",
                    "events_url": "https://api.github.com/users/slsay/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/slsay/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486567,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NTY3",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
                        "name": "?????",
                        "color": "c5def5",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2019-11-29T04:38:02Z",
                "updated_at": "2019-11-29T04:38:10Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "# github branch\r\n### server\r\nserver/develop  \r\nserver/master  \r\n\r\n### web\r\nclient/develop  \r\nclient/master  \r\n\r\n## branch???\r\n### ?????\r\nserver/{mail-id}/feature/{free}\r\n\r\n### bug??\r\nserver/{mail-id}/bugfix/{free}\r\n\r\n## ????\r\n??????master??develop??????????branch merge\r\n\r\n# github issues\r\n* ?issue??label\r\n* ?????\r\n\r\n\r\n# ????\r\n\r\n* ???????????????\r\n* ??????develop??\r\n\r\n# ????\r\n\r\n* ??airbnb javascript??\r\nhttps://github.com/airbnb/javascript\r\n* ??merge??????????\r\n\r\n## "
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/4",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/4/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/4/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/4/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/4",
                "id": 530149767,
                "node_id": "MDU6SXNzdWU1MzAxNDk3Njc=",
                "number": 4,
                "title": "????",
                "user": {
                    "login": "slsay",
                    "id": 4725762,
                    "node_id": "MDQ6VXNlcjQ3MjU3NjI=",
                    "avatar_url": "https://avatars1.githubusercontent.com/u/4725762?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/slsay",
                    "html_url": "https://github.com/slsay",
                    "followers_url": "https://api.github.com/users/slsay/followers",
                    "following_url": "https://api.github.com/users/slsay/following{/other_user}",
                    "gists_url": "https://api.github.com/users/slsay/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/slsay/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/slsay/subscriptions",
                    "organizations_url": "https://api.github.com/users/slsay/orgs",
                    "repos_url": "https://api.github.com/users/slsay/repos",
                    "events_url": "https://api.github.com/users/slsay/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/slsay/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486567,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NTY3",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
                        "name": "?????",
                        "color": "c5def5",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2019-11-29T04:25:40Z",
                "updated_at": "2019-11-29T04:25:40Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "## 1. nvm\r\nhttps://github.com/coreybutler/nvm-windows\r\n\r\n## 2. nodejs\r\n??nvm??nodejs 12.x\r\n\r\n## 3. ?? mongodb 4.2.x\r\nhttps://www.mongodb.com/download-center/community\r\n\r\n## 4. ??mongodb?? robomongo???\r\nhttps://studio3t.com/download-now/\r\n\r\n## 5. git ???\r\n\r\n## 6. vs code\r\n\r\n## 7. postman"
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/3",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/3/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/3/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/3/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/3",
                "id": 530149648,
                "node_id": "MDU6SXNzdWU1MzAxNDk2NDg=",
                "number": 3,
                "title": "????",
                "user": {
                    "login": "slsay",
                    "id": 4725762,
                    "node_id": "MDQ6VXNlcjQ3MjU3NjI=",
                    "avatar_url": "https://avatars1.githubusercontent.com/u/4725762?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/slsay",
                    "html_url": "https://github.com/slsay",
                    "followers_url": "https://api.github.com/users/slsay/followers",
                    "following_url": "https://api.github.com/users/slsay/following{/other_user}",
                    "gists_url": "https://api.github.com/users/slsay/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/slsay/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/slsay/subscriptions",
                    "organizations_url": "https://api.github.com/users/slsay/orgs",
                    "repos_url": "https://api.github.com/users/slsay/repos",
                    "events_url": "https://api.github.com/users/slsay/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/slsay/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486567,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NTY3",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
                        "name": "?????",
                        "color": "c5def5",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2019-11-29T04:25:04Z",
                "updated_at": "2019-11-29T04:25:04Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "## lib\r\n* [??](https://bizcharts.net/products/bizCharts/demo#%E6%8A%98%E7%BA%BF%E5%9B%BE)\r\n* [UI?](https://ant.design/docs/react/getting-started-cn)\r\n* [mongoose](https://mongoosejs.com/)"
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/2",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/2/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/2/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/2/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/2",
                "id": 530148321,
                "node_id": "MDU6SXNzdWU1MzAxNDgzMjE=",
                "number": 2,
                "title": "????",
                "user": {
                    "login": "slsay",
                    "id": 4725762,
                    "node_id": "MDQ6VXNlcjQ3MjU3NjI=",
                    "avatar_url": "https://avatars1.githubusercontent.com/u/4725762?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/slsay",
                    "html_url": "https://github.com/slsay",
                    "followers_url": "https://api.github.com/users/slsay/followers",
                    "following_url": "https://api.github.com/users/slsay/following{/other_user}",
                    "gists_url": "https://api.github.com/users/slsay/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/slsay/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/slsay/subscriptions",
                    "organizations_url": "https://api.github.com/users/slsay/orgs",
                    "repos_url": "https://api.github.com/users/slsay/repos",
                    "events_url": "https://api.github.com/users/slsay/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/slsay/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486567,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NTY3",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
                        "name": "?????",
                        "color": "c5def5",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2019-11-29T04:17:47Z",
                "updated_at": "2019-12-02T09:06:54Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "[????_??.xlsx](https://github.com/Intern2020OJT/CT_OBJ/files/3903719/_.xlsx)\r\n"
            },
            {
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/1",
                "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
                "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/1/labels{/name}",
                "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/1/comments",
                "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/1/events",
                "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/1",
                "id": 529141543,
                "node_id": "MDU6SXNzdWU1MjkxNDE1NDM=",
                "number": 1,
                "title": "???",
                "user": {
                    "login": "slsay",
                    "id": 4725762,
                    "node_id": "MDQ6VXNlcjQ3MjU3NjI=",
                    "avatar_url": "https://avatars1.githubusercontent.com/u/4725762?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/slsay",
                    "html_url": "https://github.com/slsay",
                    "followers_url": "https://api.github.com/users/slsay/followers",
                    "following_url": "https://api.github.com/users/slsay/following{/other_user}",
                    "gists_url": "https://api.github.com/users/slsay/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/slsay/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/slsay/subscriptions",
                    "organizations_url": "https://api.github.com/users/slsay/orgs",
                    "repos_url": "https://api.github.com/users/slsay/repos",
                    "events_url": "https://api.github.com/users/slsay/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/slsay/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 1704486567,
                        "node_id": "MDU6TGFiZWwxNzA0NDg2NTY3",
                        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
                        "name": "?????",
                        "color": "c5def5",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2019-11-27T06:19:16Z",
                "updated_at": "2019-11-29T04:23:57Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "body": "[prototype.zip](https://github.com/Intern2020OJT/CT_OBJ/files/3895404/prototype.zip)\r\n"
            }
        ],
        "labels":[
            {
                "id": 1704489925,
                "node_id": "MDU6TGFiZWwxNzA0NDg5OTI1",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E4%BC%98%E5%85%88%E5%BA%A6%EF%BC%9A%E4%B8%AD",
                "name": "?????",
                "color": "56d371",
                "default": false,
                "description": ""
            },
            {
                "id": 1704490105,
                "node_id": "MDU6TGFiZWwxNzA0NDkwMTA1",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E4%BC%98%E5%85%88%E5%BA%A6%EF%BC%9A%E4%BD%8E",
                "name": "?????",
                "color": "8750b2",
                "default": false,
                "description": ""
            },
            {
                "id": 1704489796,
                "node_id": "MDU6TGFiZWwxNzA0NDg5Nzk2",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E4%BC%98%E5%85%88%E5%BA%A6%EF%BC%9A%E9%AB%98",
                "name": "?????",
                "color": "ff0000",
                "default": false,
                "description": ""
            },
            {
                "id": 1704490358,
                "node_id": "MDU6TGFiZWwxNzA0NDkwMzU4",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E6%94%B9%E5%96%84",
                "name": "?????",
                "color": "8fb515",
                "default": false,
                "description": "?????????"
            },
            {
                "id": 1704486567,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NTY3",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
                "name": "?????",
                "color": "c5def5",
                "default": false,
                "description": ""
            },
            {
                "id": 1704486730,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                "name": "?????or????",
                "color": "fce325",
                "default": false,
                "description": ""
            },
            {
                "id": 1704491139,
                "node_id": "MDU6TGFiZWwxNzA0NDkxMTM5",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9AAPI",
                "name": "???API",
                "color": "414fbf",
                "default": false,
                "description": ""
            },
            {
                "id": 1704490958,
                "node_id": "MDU6TGFiZWwxNzA0NDkwOTU4",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9A%E5%89%8D%E7%AB%AF",
                "name": "?????",
                "color": "e99695",
                "default": false,
                "description": ""
            },
            {
                "id": 1704488956,
                "node_id": "MDU6TGFiZWwxNzA0NDg4OTU2",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E7%8A%B6%E6%80%81%EF%BC%9ADo",
                "name": "???Do",
                "color": "3cc173",
                "default": false,
                "description": ""
            },
            {
                "id": 1704489108,
                "node_id": "MDU6TGFiZWwxNzA0NDg5MTA4",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E7%8A%B6%E6%80%81%EF%BC%9ADoing",
                "name": "???Doing",
                "color": "ff6bfc",
                "default": false,
                "description": ""
            },
            {
                "id": 1704489186,
                "node_id": "MDU6TGFiZWwxNzA0NDg5MTg2",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E7%8A%B6%E6%80%81%EF%BC%9ADone",
                "name": "???Done",
                "color": "577507",
                "default": false,
                "description": ""
            }
        ],
        "language":{},
    }
]