/* eslint-disable max-len */
exports.introsData = [
  {
    id: 223835009,
    node_id: "MDEwOlJlcG9zaXRvcnkyMjM4MzUwMDk=",
    name: "CT_OBJ",
    full_name: "Intern2020OJT/CT_OBJ",
    private: false,
    owner: {
      login: "Intern2020OJT",
      id: 56333136,
      node_id: "MDEyOk9yZ2FuaXphdGlvbjU2MzMzMTM2",
      avatar_url: "https://avatars0.githubusercontent.com/u/56333136?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Intern2020OJT",
      html_url: "https://github.com/Intern2020OJT",
      followers_url: "https://api.github.com/users/Intern2020OJT/followers",
      following_url: "https://api.github.com/users/Intern2020OJT/following{/other_user}",
      gists_url: "https://api.github.com/users/Intern2020OJT/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Intern2020OJT/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Intern2020OJT/subscriptions",
      organizations_url: "https://api.github.com/users/Intern2020OJT/orgs",
      repos_url: "https://api.github.com/users/Intern2020OJT/repos",
      events_url: "https://api.github.com/users/Intern2020OJT/events{/privacy}",
      received_events_url: "https://api.github.com/users/Intern2020OJT/received_events",
      type: "Organization",
      site_admin: false,
    },
    html_url: "https://github.com/Intern2020OJT/CT_OBJ",
    description: "github issues analytics",
    fork: false,
    url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
    forks_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/forks",
    keys_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/keys{/key_id}",
    collaborators_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/teams",
    hooks_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/hooks",
    issue_events_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/events{/number}",
    events_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/events",
    assignees_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/assignees{/user}",
    branches_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/branches{/branch}",
    tags_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/tags",
    blobs_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/statuses/{sha}",
    languages_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/languages",
    stargazers_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/stargazers",
    contributors_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/contributors",
    subscribers_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/subscribers",
    subscription_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/subscription",
    commits_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/commits{/sha}",
    git_commits_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/git/commits{/sha}",
    comments_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/comments{/number}",
    issue_comment_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/contents/{+path}",
    compare_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/merges",
    archive_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/downloads",
    issues_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues{/number}",
    pulls_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/pulls{/number}",
    milestones_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/milestones{/number}",
    notifications_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels{/name}",
    releases_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/releases{/id}",
    deployments_url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/deployments",
    created_at: "2019-11-25T01:05:38Z",
    updated_at: "2019-12-11T01:28:33Z",
    pushed_at: "2019-12-18T02:28:44Z",
    git_url: "git://github.com/Intern2020OJT/CT_OBJ.git",
    ssh_url: "git@github.com:Intern2020OJT/CT_OBJ.git",
    clone_url: "https://github.com/Intern2020OJT/CT_OBJ.git",
    svn_url: "https://github.com/Intern2020OJT/CT_OBJ",
    homepage: "https://intern2020ojt.github.io/CT_OBJ/",
    size: 2049,
    stargazers_count: 0,
    watchers_count: 0,
    language: {},
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 21,
    license: null,
    forks: 0,
    open_issues: 21,
    watchers: 0,
    default_branch: "master",
    temp_clone_token: null,
    organization: {
      login: "Intern2020OJT",
      id: 56333136,
      node_id: "MDEyOk9yZ2FuaXphdGlvbjU2MzMzMTM2",
      avatar_url: "https://avatars0.githubusercontent.com/u/56333136?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Intern2020OJT",
      html_url: "https://github.com/Intern2020OJT",
      followers_url: "https://api.github.com/users/Intern2020OJT/followers",
      following_url: "https://api.github.com/users/Intern2020OJT/following{/other_user}",
      gists_url: "https://api.github.com/users/Intern2020OJT/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Intern2020OJT/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Intern2020OJT/subscriptions",
      organizations_url: "https://api.github.com/users/Intern2020OJT/orgs",
      repos_url: "https://api.github.com/users/Intern2020OJT/repos",
      events_url: "https://api.github.com/users/Intern2020OJT/events{/privacy}",
      received_events_url: "https://api.github.com/users/Intern2020OJT/received_events",
      type: "Organization",
      site_admin: false,
    },
    network_count: 0,
    subscribers_count: 3,
    labels: [
      {
        id: 1704489925,
        node_id: "MDU6TGFiZWwxNzA0NDg5OTI1",
        url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E4%BC%98%E5%85%88%E5%BA%A6%EF%BC%9A%E4%B8%AD",
        name: "优先度：中",
        color: "56d371",
        default: false,
        description: "",
      },
      {
        id: 1704490105,
        node_id: "MDU6TGFiZWwxNzA0NDkwMTA1",
        url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E4%BC%98%E5%85%88%E5%BA%A6%EF%BC%9A%E4%BD%8E",
        name: "优先度：低",
        color: "8750b2",
        default: false,
        description: "",
      },
      {
        id: 1704489796,
        node_id: "MDU6TGFiZWwxNzA0NDg5Nzk2",
        url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E4%BC%98%E5%85%88%E5%BA%A6%EF%BC%9A%E9%AB%98",
        name: "优先度：高",
        color: "ff0000",
        default: false,
        description: "",
      },
      {
        id: 1704490358,
        node_id: "MDU6TGFiZWwxNzA0NDkwMzU4",
        url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E6%94%B9%E5%96%84",
        name: "分类：改善",
        color: "8fb515",
        default: false,
        description: "想法，今后想做的事",
      },
      {
        id: 1704486567,
        node_id: "MDU6TGFiZWwxNzA0NDg2NTY3",
        url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
        name: "分类：资料",
        color: "c5def5",
        default: false,
        description: "",
      },
      {
        id: 1704486730,
        node_id: "MDU6TGFiZWwxNzA0NDg2NzMw",
        url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
        name: "分类：问题or经验分享",
        color: "fce325",
        default: false,
        description: "",
      },
      {
        id: 1704491139,
        node_id: "MDU6TGFiZWwxNzA0NDkxMTM5",
        url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9AAPI",
        name: "开发：API",
        color: "414fbf",
        default: false,
        description: "",
      },
      {
        id: 1704490958,
        node_id: "MDU6TGFiZWwxNzA0NDkwOTU4",
        url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9A%E5%89%8D%E7%AB%AF",
        name: "开发：前端",
        color: "e99695",
        default: false,
        description: "",
      },
      {
        id: 1704488956,
        node_id: "MDU6TGFiZWwxNzA0NDg4OTU2",
        url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E7%8A%B6%E6%80%81%EF%BC%9ADo",
        name: "状态：Do",
        color: "3cc173",
        default: false,
        description: "",
      },
      {
        id: 1704489108,
        node_id: "MDU6TGFiZWwxNzA0NDg5MTA4",
        url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E7%8A%B6%E6%80%81%EF%BC%9ADoing",
        name: "状态：Doing",
        color: "ff6bfc",
        default: false,
        description: "",
      },
      {
        id: 1704489186,
        node_id: "MDU6TGFiZWwxNzA0NDg5MTg2",
        url: "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E7%8A%B6%E6%80%81%EF%BC%9ADone",
        name: "状态：Done",
        color: "577507",
        default: false,
        description: "",
      },
    ],
  },
];
