exports.test = [
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/49",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/49/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/49/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/49/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/49",
        "id": 536164230,
        "node_id": "MDU6SXNzdWU1MzYxNjQyMzA=",
        "number": 49,
        "title": "数据库数据格式",
        "user": {
            "login": "airoucat",
            "id": 28886702,
            "node_id": "MDQ6VXNlcjI4ODg2NzAy",
            "avatar_url": "https://avatars3.githubusercontent.com/u/28886702?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/airoucat",
            "html_url": "https://github.com/airoucat",
            "followers_url": "https://api.github.com/users/airoucat/followers",
            "following_url": "https://api.github.com/users/airoucat/following{/other_user}",
            "gists_url": "https://api.github.com/users/airoucat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/airoucat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/airoucat/subscriptions",
            "organizations_url": "https://api.github.com/users/airoucat/orgs",
            "repos_url": "https://api.github.com/users/airoucat/repos",
            "events_url": "https://api.github.com/users/airoucat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/airoucat/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-12-11T06:10:50Z",
        "updated_at": "2019-12-12T07:49:04Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "```\r\n{\r\n    \"name\": //项目名\r\n    \"labels\":{\r\n                \"name\":\r\n                \"name\":\r\n                ...\r\n             }//项目所含所有label\r\n    \"issues\":{\r\n                \"title\":\r\n                \"html_url\":\r\n                \"labels\"://当前issues所含label\r\n                \"state\":\r\n                \"assignees\":\r\n                \"comments\":\r\n                \"created_at\":\r\n                \"closed_at\":null\r\n             }\r\n     \"languages\":\r\n}\r\n```"
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/43",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/43/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/43/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/43/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/43",
        "id": 536098033,
        "node_id": "MDU6SXNzdWU1MzYwOTgwMzM=",
        "number": 43,
        "title": "往数据建库存数据",
        "user": {
            "login": "Shanxiaolin",
            "id": 55526635,
            "node_id": "MDQ6VXNlcjU1NTI2NjM1",
            "avatar_url": "https://avatars3.githubusercontent.com/u/55526635?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Shanxiaolin",
            "html_url": "https://github.com/Shanxiaolin",
            "followers_url": "https://api.github.com/users/Shanxiaolin/followers",
            "following_url": "https://api.github.com/users/Shanxiaolin/following{/other_user}",
            "gists_url": "https://api.github.com/users/Shanxiaolin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Shanxiaolin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Shanxiaolin/subscriptions",
            "organizations_url": "https://api.github.com/users/Shanxiaolin/orgs",
            "repos_url": "https://api.github.com/users/Shanxiaolin/repos",
            "events_url": "https://api.github.com/users/Shanxiaolin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Shanxiaolin/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486730,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                "name": "分类：问题or经验分享",
                "color": "fce325",
                "default": false,
                "description": ""
            },
            {
                "id": 1704491139,
                "node_id": "MDU6TGFiZWwxNzA0NDkxMTM5",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9AAPI",
                "name": "开发：API",
                "color": "414fbf",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-12-11T02:09:02Z",
        "updated_at": "2019-12-11T07:07:20Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "### 文件功能概览\r\n- user.js  存放数据\r\n- import_uesr.js  导入数据的\r\n- mod_user.js 定义导入的数据类型，定义数据库名字\r\n![image](https://user-images.githubusercontent.com/55526635/70584647-c770fa00-1bfc-11ea-999d-86fb62e1c776.png)\r\n`const ModelTest = new Model(DB_NAME_ISSUE, SCHEMA_SXL, Test)`\r\n- DB_NAME_ISSUE应该在db.js或其他地方用到过换为其他的会报错，第二个参数可以自定义\r\n### 一个导入数据库数据的例子\r\ntest.js\r\n```\r\nexports.test = [\r\n    { genre: 'Sports', sold: 8 },  \r\n    { genre: 'Action', sold: 9},\r\n    { genre: 'Shooter', sold: 6 },\r\n    { genre: 'Strategy', sold: 8},\r\n    { genre: 'Other', sold: 7}\r\n  ]  \r\n```\r\nimport_test.js\r\n```\r\nconst { test }           = require(\"./test\");\r\nconst ModelTest       = require(\"../modules/system/models/mod_test\");\r\n\r\nconst importTest = async () => {\r\n  try {\r\n    await Promise.all(test.map(async (record) => {\r\n      await ModelTest.create({...record});\r\n    }));\r\n  } catch (err) {\r\n    throw err;\r\n  }\r\n};\r\n\r\nimportTest().then(() => {\r\n  console.log('ok');\r\n  process.exit();\r\n}).catch((err) => {\r\n  console.log('error');\r\n  console.log(err);\r\n  process.exit();\r\n});\r\n```\r\nmod_test.js\r\n```\r\nconst SchemaCommon    = require(\"../../mod_base\");\r\nconst mongoose   = require(\"mongoose\");\r\nconst Model           = require(\"../../../core/model\");\r\nconst constant        = require(\"../../../core/constant\");\r\nconst { Schema } = mongoose;\r\nconst { Mixed }   = Schema.Types;\r\nconst { DB_NAME_ISSUE, SCHEMA_SXL } = constant;\r\n\r\nconst { BaseSchema } = SchemaCommon;\r\n\r\nconst Test = new BaseSchema({\r\n  genre:              { type: String, description: \"横坐标\" },\r\n  sold:               { type: Mixed, description: \"纵坐标\" },  \r\n});\r\n\r\nconst ModelTest = new Model(DB_NAME_ISSUE, SCHEMA_SXL, Test);\r\n\r\nmodule.exports = ModelTest;\r\n\r\n```\r\n- import_test.js内容放在ctrl_  下面作为一种方法调用\r\n \r\n"
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/41",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/41/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/41/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/41/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/41",
        "id": 536084919,
        "node_id": "MDU6SXNzdWU1MzYwODQ5MTk=",
        "number": 41,
        "title": "服务端GET方法获得客户端传来的参数",
        "user": {
            "login": "Progyang",
            "id": 50037121,
            "node_id": "MDQ6VXNlcjUwMDM3MTIx",
            "avatar_url": "https://avatars3.githubusercontent.com/u/50037121?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Progyang",
            "html_url": "https://github.com/Progyang",
            "followers_url": "https://api.github.com/users/Progyang/followers",
            "following_url": "https://api.github.com/users/Progyang/following{/other_user}",
            "gists_url": "https://api.github.com/users/Progyang/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Progyang/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Progyang/subscriptions",
            "organizations_url": "https://api.github.com/users/Progyang/orgs",
            "repos_url": "https://api.github.com/users/Progyang/repos",
            "events_url": "https://api.github.com/users/Progyang/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Progyang/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486730,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                "name": "分类：问题or经验分享",
                "color": "fce325",
                "default": false,
                "description": ""
            },
            {
                "id": 1704491139,
                "node_id": "MDU6TGFiZWwxNzA0NDkxMTM5",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9AAPI",
                "name": "开发：API",
                "color": "414fbf",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-12-11T01:18:32Z",
        "updated_at": "2019-12-11T01:18:32Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "#### 客户端\r\n![image](https://user-images.githubusercontent.com/50037121/70582884-fab08a80-1bf6-11ea-87f6-818b0e6b96be.png)\r\n#### 服务端\r\n![image](https://user-images.githubusercontent.com/50037121/70582944-2fbcdd00-1bf7-11ea-8d0b-772c41ec90be.png)\r\n"
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/34",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/34/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/34/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/34/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/34",
        "id": 535498202,
        "node_id": "MDU6SXNzdWU1MzU0OTgyMDI=",
        "number": 34,
        "title": "连接数据库的逻辑",
        "user": {
            "login": "Shanxiaolin",
            "id": 55526635,
            "node_id": "MDQ6VXNlcjU1NTI2NjM1",
            "avatar_url": "https://avatars3.githubusercontent.com/u/55526635?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Shanxiaolin",
            "html_url": "https://github.com/Shanxiaolin",
            "followers_url": "https://api.github.com/users/Shanxiaolin/followers",
            "following_url": "https://api.github.com/users/Shanxiaolin/following{/other_user}",
            "gists_url": "https://api.github.com/users/Shanxiaolin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Shanxiaolin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Shanxiaolin/subscriptions",
            "organizations_url": "https://api.github.com/users/Shanxiaolin/orgs",
            "repos_url": "https://api.github.com/users/Shanxiaolin/repos",
            "events_url": "https://api.github.com/users/Shanxiaolin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Shanxiaolin/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486730,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                "name": "分类：问题or经验分享",
                "color": "fce325",
                "default": false,
                "description": ""
            },
            {
                "id": 1704491139,
                "node_id": "MDU6TGFiZWwxNzA0NDkxMTM5",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9AAPI",
                "name": "开发：API",
                "color": "414fbf",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 3,
        "created_at": "2019-12-10T05:12:12Z",
        "updated_at": "2019-12-11T07:31:15Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "### 调用顺序\r\n- index.js中的api   通过ctrlUser.simpleLogin调用  \r\n- ctr_user   调用\r\n- ModelUser (mod_user.js) 调用\r\n- Model (model.js) 调用\r\n- db.js \r\n### 中间解释\r\n- index.js 中如果是post方法需要请求体在ctr_user中定义\r\n  `const { name, pass } = req.body`\r\n- 获取图形数据主要是写get的api，操作获取数据根据这个我做了以下调研\r\n- ModelUser创建了一个model对象，用这个对象的方法（操作mongodb数据库的方法\r\n）调用model.js\r\n- 接着调用model.js构造函数（在构造函数里连接数据库）\r\n```\r\nconstructor(code, name, scheme) {\r\n    const conn = db.createConnection(code);\r\n    this.m = conn.model(name, scheme);//创建新的模型\r\n    //this.m 包含两个模型 Model { User } Model { Token }（这个是调用了两次，我只找到了一次调用）\r\n```\r\n- 调用完上面的连接数据库方法后，开始执行model.js里边的方法，model.js里边定义的方法都是操作mongodb数据库的方法\r\n### 一个调取数据库数据的get方法参考例子\r\nctrl_modul.js\r\n```\r\nconst log         = require(\"../../../core/logger\");\r\nconst ModelUser    = require(\"../models/mod_user\");\r\nexports.modul = async (req) => {\r\n  log.info(\"user.modul() start.\");\r\n  try {\r\n    log.info(\"ctr_modul 1\")\r\n    const id = '5de73eba2875ec1c9cb61997';\r\n    log.info(\"ctr_modul 2\")\r\n    const projection = \"\";\r\n    log.info(\"ctr_modul 3\")\r\n    const message = await ModelUser.get(id, projection);\r\n    log.info(\"ctr_modul 4\")\r\n    return message;\r\n  } catch (err) {\r\n    log.info(\"user.modul() error.\");\r\n    log.error(err);\r\n    throw err;\r\n  }\r\n};\r\n ```\r\nindex.js下api\r\n```\r\napp.get(`/${appName}/openingissues`, async (req,res) => {\r\n    try {\r\n      const result = await ctrlModul.modul(req);\r\n      response.sendSuccess(res, result);\r\n    } catch (err) {\r\n      response.sendError(res,err);\r\n    }\r\n  }); \r\n```\r\n\r\n"
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/28",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/28/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/28/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/28/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/28",
        "id": 534678526,
        "node_id": "MDU6SXNzdWU1MzQ2Nzg1MjY=",
        "number": 28,
        "title": "Tooltip的一些自定义属性",
        "user": {
            "login": "Progyang",
            "id": 50037121,
            "node_id": "MDQ6VXNlcjUwMDM3MTIx",
            "avatar_url": "https://avatars3.githubusercontent.com/u/50037121?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Progyang",
            "html_url": "https://github.com/Progyang",
            "followers_url": "https://api.github.com/users/Progyang/followers",
            "following_url": "https://api.github.com/users/Progyang/following{/other_user}",
            "gists_url": "https://api.github.com/users/Progyang/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Progyang/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Progyang/subscriptions",
            "organizations_url": "https://api.github.com/users/Progyang/orgs",
            "repos_url": "https://api.github.com/users/Progyang/repos",
            "events_url": "https://api.github.com/users/Progyang/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Progyang/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486730,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                "name": "分类：问题or经验分享",
                "color": "fce325",
                "default": false,
                "description": ""
            },
            {
                "id": 1704490958,
                "node_id": "MDU6TGFiZWwxNzA0NDkwOTU4",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9A%E5%89%8D%E7%AB%AF",
                "name": "开发：前端",
                "color": "e99695",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-12-09T04:12:07Z",
        "updated_at": "2019-12-09T04:12:24Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "[官方API文档](https://bizcharts.net/products/bizCharts/api/graphic)\r\n```\r\n                <Geom\r\n                   type=\"interval\"\r\n                    position=\"shortName*comments\"\r\n                    tooltip={['fullName*comments', (fullName, comments) => {\r\n                        return {\r\n                          //自定义 tooltip 上显示的 title 显示内容等。\r\n                          name: fullName,\r\n                          title: fullName,\r\n                          value: comments\r\n                        };\r\n                      }]}>\r\n                    <Label content={['comments']} />{' '}\r\n                </Geom> \r\n```\r\n**在Geom(绘图标签)标签内修改tooltip属性即可**\r\n![image](https://user-images.githubusercontent.com/50037121/70406811-e0eb3800-1a7c-11ea-8cc7-1cf4784bc94e.png)\r\n这部分代码用于传入数据\r\n![image](https://user-images.githubusercontent.com/50037121/70406868-13953080-1a7d-11ea-9400-dd482110f6c9.png)\r\n\r\n\r\n"
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/24",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/24/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/24/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/24/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/24",
        "id": 533825556,
        "node_id": "MDU6SXNzdWU1MzM4MjU1NTY=",
        "number": 24,
        "title": "UI库内组件的文本样式不能自定义",
        "user": {
            "login": "AyaseEUmi",
            "id": 49441287,
            "node_id": "MDQ6VXNlcjQ5NDQxMjg3",
            "avatar_url": "https://avatars2.githubusercontent.com/u/49441287?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/AyaseEUmi",
            "html_url": "https://github.com/AyaseEUmi",
            "followers_url": "https://api.github.com/users/AyaseEUmi/followers",
            "following_url": "https://api.github.com/users/AyaseEUmi/following{/other_user}",
            "gists_url": "https://api.github.com/users/AyaseEUmi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/AyaseEUmi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/AyaseEUmi/subscriptions",
            "organizations_url": "https://api.github.com/users/AyaseEUmi/orgs",
            "repos_url": "https://api.github.com/users/AyaseEUmi/repos",
            "events_url": "https://api.github.com/users/AyaseEUmi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/AyaseEUmi/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704489925,
                "node_id": "MDU6TGFiZWwxNzA0NDg5OTI1",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E4%BC%98%E5%85%88%E5%BA%A6%EF%BC%9A%E4%B8%AD",
                "name": "优先度：中",
                "color": "56d371",
                "default": false,
                "description": ""
            },
            {
                "id": 1704486730,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                "name": "分类：问题or经验分享",
                "color": "fce325",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-12-06T08:47:47Z",
        "updated_at": "2019-12-09T04:06:21Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": ""
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/12",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/12/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/12/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/12/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/12",
        "id": 532466157,
        "node_id": "MDU6SXNzdWU1MzI0NjYxNTc=",
        "number": 12,
        "title": "Card组件的用法",
        "user": {
            "login": "Progyang",
            "id": 50037121,
            "node_id": "MDQ6VXNlcjUwMDM3MTIx",
            "avatar_url": "https://avatars3.githubusercontent.com/u/50037121?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Progyang",
            "html_url": "https://github.com/Progyang",
            "followers_url": "https://api.github.com/users/Progyang/followers",
            "following_url": "https://api.github.com/users/Progyang/following{/other_user}",
            "gists_url": "https://api.github.com/users/Progyang/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Progyang/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Progyang/subscriptions",
            "organizations_url": "https://api.github.com/users/Progyang/orgs",
            "repos_url": "https://api.github.com/users/Progyang/repos",
            "events_url": "https://api.github.com/users/Progyang/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Progyang/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486730,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                "name": "分类：问题or经验分享",
                "color": "fce325",
                "default": false,
                "description": ""
            },
            {
                "id": 1704490958,
                "node_id": "MDU6TGFiZWwxNzA0NDkwOTU4",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9A%E5%89%8D%E7%AB%AF",
                "name": "开发：前端",
                "color": "e99695",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-12-04T05:51:55Z",
        "updated_at": "2019-12-04T05:54:46Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "```\r\nimport React, { useState } from 'react';\r\nimport { Card } from 'antd';\r\n\r\nimport SClassifyLablesAnalyseBar from './SClassifyLablesAnalyseBar';\r\nimport SClassifyLablesAnalysePie from './SClassifyLablesAnalysePie';\r\n\r\nconst SClassifyLablesAnalyse = () => {\r\n  const [tabs, setState] = useState('bar');\r\n  \r\n  const tabList = [\r\n    {\r\n      key: 'bar',\r\n      tab: '柱状图',\r\n    },\r\n    {\r\n      key: 'pie',\r\n      tab: '饼状图',\r\n    },\r\n  ];\r\n  \r\n  const contentList = {\r\n    bar: <SClassifyLablesAnalyseBar />,\r\n    pie: <SClassifyLablesAnalysePie />,\r\n  };\r\n\r\n  return (\r\n    <Card\r\n      style={{ width: '600px', height: '500px' }}\r\n      title=\"Lables分析\"\r\n      tabList={tabList}\r\n      activeTabKey={tabs}\r\n      onTabChange={key => {\r\n        setState(key);\r\n      }}\r\n    >\r\n      {contentList[tabs]}\r\n    </Card>\r\n  );\r\n};\r\n\r\nexport default SClassifyLablesAnalyse;\r\n```\r\ncontentList 是一个键值对类型的数据,键单独标识一个tab,而值则表示这个tab下包含的内容,而定义为组件则可实现如下效果\r\n![image](https://user-images.githubusercontent.com/50037121/70116403-9729d880-169d-11ea-8dd6-4e834970eaf7.png)\r\n![image](https://user-images.githubusercontent.com/50037121/70116409-9ee97d00-169d-11ea-9f76-04e3d6610c27.png)\r\n\r\n"
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/11",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/11/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/11/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/11/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/11",
        "id": 532465568,
        "node_id": "MDU6SXNzdWU1MzI0NjU1Njg=",
        "number": 11,
        "title": "关于DOM的封装与调用",
        "user": {
            "login": "Progyang",
            "id": 50037121,
            "node_id": "MDQ6VXNlcjUwMDM3MTIx",
            "avatar_url": "https://avatars3.githubusercontent.com/u/50037121?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Progyang",
            "html_url": "https://github.com/Progyang",
            "followers_url": "https://api.github.com/users/Progyang/followers",
            "following_url": "https://api.github.com/users/Progyang/following{/other_user}",
            "gists_url": "https://api.github.com/users/Progyang/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Progyang/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Progyang/subscriptions",
            "organizations_url": "https://api.github.com/users/Progyang/orgs",
            "repos_url": "https://api.github.com/users/Progyang/repos",
            "events_url": "https://api.github.com/users/Progyang/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Progyang/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486730,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                "name": "分类：问题or经验分享",
                "color": "fce325",
                "default": false,
                "description": ""
            },
            {
                "id": 1704490958,
                "node_id": "MDU6TGFiZWwxNzA0NDkwOTU4",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9A%E5%89%8D%E7%AB%AF",
                "name": "开发：前端",
                "color": "e99695",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-12-04T05:49:55Z",
        "updated_at": "2019-12-05T00:46:55Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "![image](https://user-images.githubusercontent.com/50037121/70115998-69905f80-169c-11ea-8ba5-e554d855434c.png)\r\n如图,定义一个SClassifyAnalyse组件,他使用<SClassifyLablesAnalyse /><SClassifyAssigneesAnalyse />这两个标签调用了另外两个组件\r\n![image](https://user-images.githubusercontent.com/50037121/70116094-ad836480-169c-11ea-9537-157653e9ac82.png)\r\n而在他的父元素中,使用<SClassifyAnalyse />这个标签来调用他\r\n![image](https://user-images.githubusercontent.com/50037121/70116136-c7bd4280-169c-11ea-869a-4f22dec3c9f7.png)\r\n最后放在SHome中,统一由app.jsx渲染即可\r\n"
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/10",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/10/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/10/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/10/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/10",
        "id": 532399053,
        "node_id": "MDU6SXNzdWU1MzIzOTkwNTM=",
        "number": 10,
        "title": "后端编写一个简单的API",
        "user": {
            "login": "Shanxiaolin",
            "id": 55526635,
            "node_id": "MDQ6VXNlcjU1NTI2NjM1",
            "avatar_url": "https://avatars3.githubusercontent.com/u/55526635?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Shanxiaolin",
            "html_url": "https://github.com/Shanxiaolin",
            "followers_url": "https://api.github.com/users/Shanxiaolin/followers",
            "following_url": "https://api.github.com/users/Shanxiaolin/following{/other_user}",
            "gists_url": "https://api.github.com/users/Shanxiaolin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Shanxiaolin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Shanxiaolin/subscriptions",
            "organizations_url": "https://api.github.com/users/Shanxiaolin/orgs",
            "repos_url": "https://api.github.com/users/Shanxiaolin/repos",
            "events_url": "https://api.github.com/users/Shanxiaolin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Shanxiaolin/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486730,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                "name": "分类：问题or经验分享",
                "color": "fce325",
                "default": false,
                "description": ""
            },
            {
                "id": 1704491139,
                "node_id": "MDU6TGFiZWwxNzA0NDkxMTM5",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9AAPI",
                "name": "开发：API",
                "color": "414fbf",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-12-04T02:05:26Z",
        "updated_at": "2019-12-05T01:41:41Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "### 后端工作的逻辑个人理解\r\n- app.js是一个restAPI服务启动项，是node.js的一种方法，觉得抽象可以跟着下面教程自己做一个[Node.js RESTful API](https://www.runoob.com/nodejs/nodejs-restful-api.html)，我们项目中的npm run start命令等价于菜鸟教程上的node...等价与我们项目上的node app.js命令。\r\n### 具体在哪里写，如何写\r\n- 在src->routes->index.js下面写API\r\n- 在src->modules->system->controllers可以自己建js文件也可以直接在杨哥建好的两个文件下直接写\r\n- ctrl_user.js\r\n```\r\nexports.openingissues = async (req) => {\r\n  log.info(\"get openingissues\");\r\n  try{\r\n      res = 2;\r\n      return (res);\r\n    }\r\n  catch(err){\r\n    log.info(\"get openingissues err\")\r\n    log.err(err)\r\n    throw err\r\n  }\r\n}\r\n```\r\n- index.js\r\n```\r\napp.get(`/${appName}/openingissues`, async (req,res) => {\r\n    try {\r\n      // console.log(1)\r\n      const result = await ctrlUser.openingissues(req);\r\n      response.sendSuccess(res, result);\r\n    } catch (err) {\r\n      response.sendError(res,err);\r\n    }\r\n  });\r\n```\r\n启动：npm run start\r\npostman 测试\r\nhttp://localhost:3000/issues/openingissues\r\n端口号的改写在config->app.js\r\n${appName}也是在config->app.js   name: \"issues\",  即 ${appName}=issues"
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/9",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/9/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/9/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/9/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/9",
        "id": 532386643,
        "node_id": "MDU6SXNzdWU1MzIzODY2NDM=",
        "number": 9,
        "title": "前端加入新页面与页面跳转（路由实现）个人理解。",
        "user": {
            "login": "Shanxiaolin",
            "id": 55526635,
            "node_id": "MDQ6VXNlcjU1NTI2NjM1",
            "avatar_url": "https://avatars3.githubusercontent.com/u/55526635?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Shanxiaolin",
            "html_url": "https://github.com/Shanxiaolin",
            "followers_url": "https://api.github.com/users/Shanxiaolin/followers",
            "following_url": "https://api.github.com/users/Shanxiaolin/following{/other_user}",
            "gists_url": "https://api.github.com/users/Shanxiaolin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Shanxiaolin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Shanxiaolin/subscriptions",
            "organizations_url": "https://api.github.com/users/Shanxiaolin/orgs",
            "repos_url": "https://api.github.com/users/Shanxiaolin/repos",
            "events_url": "https://api.github.com/users/Shanxiaolin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Shanxiaolin/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486730,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                "name": "分类：问题or经验分享",
                "color": "fce325",
                "default": false,
                "description": ""
            },
            {
                "id": 1704490958,
                "node_id": "MDU6TGFiZWwxNzA0NDkwOTU4",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%BC%80%E5%8F%91%EF%BC%9A%E5%89%8D%E7%AB%AF",
                "name": "开发：前端",
                "color": "e99695",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-12-04T01:41:59Z",
        "updated_at": "2019-12-04T01:42:48Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "### 加入页面步骤\r\n- 第一步在src->modules->system->scenes下建立自己的 jsx 文件，写法参考Shome.jsx。\r\n- 第二步在src->utils->constants.js 添加自己页面的路由信息，写法参考杨哥写好的。\r\n- 第三步在app.jsx引入自己的页面我加的页面是Stest\r\n`import STest from './modules/system/scenes/STest';`\r\n- 第四步在app.jsx中有一个hook写法加入你的路由信息，我的是component={STest}  ;\r\n```\r\n const App = () => {\r\n  return (\r\n    <IntlProvider locale={navigator.language} messages={chooseLocale()}>\r\n      <Router basename={process.env.PUBLIC_URL}>\r\n        { <Switch>\r\n          <PublicRoute path=\"/\" exact component={SLogin} />\r\n          <PublicRoute path={ROUTE_LOGIN} component={SLogin} />\r\n          <PrivateRoute path={ROUTE_TEST} component={STest} />\r\n          <PrivateRoute path={ROUTE_HOME} component={SHome} />\r\n          <Route path={ROUTE_ERROR} exact component={SInternalServerError} />\r\n          <Route path=\"*\" component={SNotFound} />\r\n        </Switch> }\r\n      </Router>\r\n    </IntlProvider>\r\n  );\r\n};\r\n```\r\n`<PrivateRoute><PublicRoute>`我把它们理解为路由组件，规定了一些跳转规则\r\n```\r\nconst PrivateRoute = ({ component: Component, ...rest }) => {\r\n  return (\r\n    <Route\r\n      {...rest}\r\n      render={props =>\r\n        storage.isAuthenticatedUser() ? (\r\n          <CDefaultLayout>\r\n            <Component {...props} />\r\n          </CDefaultLayout>\r\n        ) : (\r\n          <Redirect to={ROUTE_LOGIN} />\r\n        )\r\n      }\r\n    />\r\n  );\r\n};\r\n```\r\n这个是私有路由；执行的功能是如果login界面认证成功，渲染一个CDefaultLayout组件并且跳转到私有路由下（我这里有两个私有路由test,home好像是test在前面的原因login认证成功直接跳转到了test）不成功就跳转login页面。\r\n公有路由没太看懂\r\n\r\n"
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/8",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/8/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/8/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/8/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/8",
        "id": 531675281,
        "node_id": "MDU6SXNzdWU1MzE2NzUyODE=",
        "number": 8,
        "title": "在使用图库时报错Module not found: Can't resolve '@antv/data-set' in 'C:\\Users\\sxl\\CT_Client\\src\\modules\\system\\scenes'",
        "user": {
            "login": "Shanxiaolin",
            "id": 55526635,
            "node_id": "MDQ6VXNlcjU1NTI2NjM1",
            "avatar_url": "https://avatars3.githubusercontent.com/u/55526635?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Shanxiaolin",
            "html_url": "https://github.com/Shanxiaolin",
            "followers_url": "https://api.github.com/users/Shanxiaolin/followers",
            "following_url": "https://api.github.com/users/Shanxiaolin/following{/other_user}",
            "gists_url": "https://api.github.com/users/Shanxiaolin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Shanxiaolin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Shanxiaolin/subscriptions",
            "organizations_url": "https://api.github.com/users/Shanxiaolin/orgs",
            "repos_url": "https://api.github.com/users/Shanxiaolin/repos",
            "events_url": "https://api.github.com/users/Shanxiaolin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Shanxiaolin/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486730,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NzMw",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E9%97%AE%E9%A2%98or%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB",
                "name": "分类：问题or经验分享",
                "color": "fce325",
                "default": false,
                "description": ""
            },
            {
                "id": 1704489186,
                "node_id": "MDU6TGFiZWwxNzA0NDg5MTg2",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E7%8A%B6%E6%80%81%EF%BC%9ADone",
                "name": "状态：Done",
                "color": "577507",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-12-03T02:46:07Z",
        "updated_at": "2019-12-03T02:46:07Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "这是由于缺少Module所致\r\n`npm install 此处为报错缺少的模块`"
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/7",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/7/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/7/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/7/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/7",
        "id": 530867782,
        "node_id": "MDU6SXNzdWU1MzA4Njc3ODI=",
        "number": 7,
        "title": "后端改为本地服务的方法",
        "user": {
            "login": "Progyang",
            "id": 50037121,
            "node_id": "MDQ6VXNlcjUwMDM3MTIx",
            "avatar_url": "https://avatars3.githubusercontent.com/u/50037121?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Progyang",
            "html_url": "https://github.com/Progyang",
            "followers_url": "https://api.github.com/users/Progyang/followers",
            "following_url": "https://api.github.com/users/Progyang/following{/other_user}",
            "gists_url": "https://api.github.com/users/Progyang/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Progyang/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Progyang/subscriptions",
            "organizations_url": "https://api.github.com/users/Progyang/orgs",
            "repos_url": "https://api.github.com/users/Progyang/repos",
            "events_url": "https://api.github.com/users/Progyang/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Progyang/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486567,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NTY3",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
                "name": "分类：资料",
                "color": "c5def5",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-12-02T03:35:46Z",
        "updated_at": "2019-12-02T03:35:46Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "将以下两个文件中的REACT_APP_API_URL,改为 http://localhost:3000/issues 即可\r\n ![image](https://user-images.githubusercontent.com/50037121/69928776-aa9b3f00-14f7-11ea-91b3-757d9f637a1c.png)\r\n"
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/6",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/6/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/6/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/6/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/6",
        "id": 530155059,
        "node_id": "MDU6SXNzdWU1MzAxNTUwNTk=",
        "number": 6,
        "title": "安装手顺",
        "user": {
            "login": "slsay",
            "id": 4725762,
            "node_id": "MDQ6VXNlcjQ3MjU3NjI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/4725762?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/slsay",
            "html_url": "https://github.com/slsay",
            "followers_url": "https://api.github.com/users/slsay/followers",
            "following_url": "https://api.github.com/users/slsay/following{/other_user}",
            "gists_url": "https://api.github.com/users/slsay/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/slsay/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/slsay/subscriptions",
            "organizations_url": "https://api.github.com/users/slsay/orgs",
            "repos_url": "https://api.github.com/users/slsay/repos",
            "events_url": "https://api.github.com/users/slsay/events{/privacy}",
            "received_events_url": "https://api.github.com/users/slsay/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486567,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NTY3",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
                "name": "分类：资料",
                "color": "c5def5",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-29T04:53:08Z",
        "updated_at": "2019-11-29T04:53:46Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "## 准备\r\n* 安装git\r\n* 安装nvm\r\nhttps://github.com/nvm-sh/nvm\r\n\r\n* 通过nvm安装node 12.x\r\n```sh\r\n  nvm install 12\r\n```\r\n* 安装mongodb并启动\r\n```sh\r\n$ tar -zxvf mongodb-macos-x86_64-4.2.1.tgz\r\n$ mv mongodb-macos-x86_64-4.2.1.tgz  mongodb-4.2.1\r\n$ cd mongodb-4.2.1\r\n$ mkdir data\r\n$ cd ..\r\n$ bin/mongod --dbpath ./data/\r\n// 默认端口27017\r\n```\r\n### 下载代码\r\n```sh\r\n// 前端\r\n$ git clone https://userId:password@github.com/Intern2020OJT/CT_OBJ.git client_dev\r\n$ cd client_dev\r\n$ git checkout client/develop\r\n\r\n// API\r\n$ git clone https://userId:password@github.com/Intern2020OJT/CT_OBJ.git server_dev\r\n$ cd server_dev\r\n$ git checkout server/develop\r\n```\r\n\r\n## API\r\n###  启动\r\n```sh\r\n$ cd server_dev\r\n$ nvm use 12\r\n$ npm install\r\n$ npm run start\r\n```\r\n\r\n##  导入用户数据\r\n```sh\r\n$ cd server_dev\r\n$ nvm use 12\r\n$ node ./src/tool/import_user.js\r\n```\r\n\r\n## 前端\r\n### 启动\r\n```sh\r\n$ cd client_dev\r\n$ nvm use 12\r\n$ npm install\r\n$ npm run start\r\n```\r\n### 访问\r\nhttp://localhost:5000\r\n\r\n![スクリーンショット 0031-11-29 12 52 16](https://user-images.githubusercontent.com/4725762/69844424-26eb1380-12a7-11ea-92d7-21205c1c66e2.png)\r\n"
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/5",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/5/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/5/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/5/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/5",
        "id": 530152097,
        "node_id": "MDU6SXNzdWU1MzAxNTIwOTc=",
        "number": 5,
        "title": "规则",
        "user": {
            "login": "slsay",
            "id": 4725762,
            "node_id": "MDQ6VXNlcjQ3MjU3NjI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/4725762?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/slsay",
            "html_url": "https://github.com/slsay",
            "followers_url": "https://api.github.com/users/slsay/followers",
            "following_url": "https://api.github.com/users/slsay/following{/other_user}",
            "gists_url": "https://api.github.com/users/slsay/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/slsay/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/slsay/subscriptions",
            "organizations_url": "https://api.github.com/users/slsay/orgs",
            "repos_url": "https://api.github.com/users/slsay/repos",
            "events_url": "https://api.github.com/users/slsay/events{/privacy}",
            "received_events_url": "https://api.github.com/users/slsay/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486567,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NTY3",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
                "name": "分类：资料",
                "color": "c5def5",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-29T04:38:02Z",
        "updated_at": "2019-11-29T04:38:10Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "# github branch\r\n### server\r\nserver/develop  \r\nserver/master  \r\n\r\n### web\r\nclient/develop  \r\nclient/master  \r\n\r\n## branch名规则\r\n### 新机能追加\r\nserver/{mail-id}/feature/{free}\r\n\r\n### bug修正\r\nserver/{mail-id}/bugfix/{free}\r\n\r\n## 代码提交\r\n不能直接修改master或者develop分支的代码，必须通过branch merge\r\n\r\n# github issues\r\n* 给issue添加label\r\n* 指定担当者\r\n\r\n\r\n# 代码管理\r\n\r\n* 每天下班前，提交自己当天的代码\r\n* 开发前，同步develop代码\r\n\r\n# 代码规范\r\n\r\n* 参考airbnb javascript规范\r\nhttps://github.com/airbnb/javascript\r\n* 代码merge有冲突时和相关者确认\r\n\r\n## "
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/4",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/4/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/4/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/4/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/4",
        "id": 530149767,
        "node_id": "MDU6SXNzdWU1MzAxNDk3Njc=",
        "number": 4,
        "title": "工具准备",
        "user": {
            "login": "slsay",
            "id": 4725762,
            "node_id": "MDQ6VXNlcjQ3MjU3NjI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/4725762?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/slsay",
            "html_url": "https://github.com/slsay",
            "followers_url": "https://api.github.com/users/slsay/followers",
            "following_url": "https://api.github.com/users/slsay/following{/other_user}",
            "gists_url": "https://api.github.com/users/slsay/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/slsay/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/slsay/subscriptions",
            "organizations_url": "https://api.github.com/users/slsay/orgs",
            "repos_url": "https://api.github.com/users/slsay/repos",
            "events_url": "https://api.github.com/users/slsay/events{/privacy}",
            "received_events_url": "https://api.github.com/users/slsay/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486567,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NTY3",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
                "name": "分类：资料",
                "color": "c5def5",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-29T04:25:40Z",
        "updated_at": "2019-11-29T04:25:40Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "## 1. nvm\r\nhttps://github.com/coreybutler/nvm-windows\r\n\r\n## 2. nodejs\r\n通过nvm安装nodejs 12.x\r\n\r\n## 3. 安装 mongodb 4.2.x\r\nhttps://www.mongodb.com/download-center/community\r\n\r\n## 4. 安装mongodb工具 robomongo最新版\r\nhttps://studio3t.com/download-now/\r\n\r\n## 5. git 最新版\r\n\r\n## 6. vs code\r\n\r\n## 7. postman"
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/3",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/3/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/3/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/3/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/3",
        "id": 530149648,
        "node_id": "MDU6SXNzdWU1MzAxNDk2NDg=",
        "number": 3,
        "title": "参考网站",
        "user": {
            "login": "slsay",
            "id": 4725762,
            "node_id": "MDQ6VXNlcjQ3MjU3NjI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/4725762?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/slsay",
            "html_url": "https://github.com/slsay",
            "followers_url": "https://api.github.com/users/slsay/followers",
            "following_url": "https://api.github.com/users/slsay/following{/other_user}",
            "gists_url": "https://api.github.com/users/slsay/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/slsay/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/slsay/subscriptions",
            "organizations_url": "https://api.github.com/users/slsay/orgs",
            "repos_url": "https://api.github.com/users/slsay/repos",
            "events_url": "https://api.github.com/users/slsay/events{/privacy}",
            "received_events_url": "https://api.github.com/users/slsay/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486567,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NTY3",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
                "name": "分类：资料",
                "color": "c5def5",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-29T04:25:04Z",
        "updated_at": "2019-11-29T04:25:04Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "## lib\r\n* [图库](https://bizcharts.net/products/bizCharts/demo#%E6%8A%98%E7%BA%BF%E5%9B%BE)\r\n* [UI库](https://ant.design/docs/react/getting-started-cn)\r\n* [mongoose](https://mongoosejs.com/)"
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/2",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/2/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/2/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/2/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/2",
        "id": 530148321,
        "node_id": "MDU6SXNzdWU1MzAxNDgzMjE=",
        "number": 2,
        "title": "项目管理",
        "user": {
            "login": "slsay",
            "id": 4725762,
            "node_id": "MDQ6VXNlcjQ3MjU3NjI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/4725762?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/slsay",
            "html_url": "https://github.com/slsay",
            "followers_url": "https://api.github.com/users/slsay/followers",
            "following_url": "https://api.github.com/users/slsay/following{/other_user}",
            "gists_url": "https://api.github.com/users/slsay/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/slsay/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/slsay/subscriptions",
            "organizations_url": "https://api.github.com/users/slsay/orgs",
            "repos_url": "https://api.github.com/users/slsay/repos",
            "events_url": "https://api.github.com/users/slsay/events{/privacy}",
            "received_events_url": "https://api.github.com/users/slsay/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486567,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NTY3",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
                "name": "分类：资料",
                "color": "c5def5",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-11-29T04:17:47Z",
        "updated_at": "2019-12-02T09:06:54Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "[案件管理_参考.xlsx](https://github.com/Intern2020OJT/CT_OBJ/files/3903719/_.xlsx)\r\n"
    },
    {
        "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/1",
        "repository_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ",
        "labels_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/1/labels{/name}",
        "comments_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/1/comments",
        "events_url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/issues/1/events",
        "html_url": "https://github.com/Intern2020OJT/CT_OBJ/issues/1",
        "id": 529141543,
        "node_id": "MDU6SXNzdWU1MjkxNDE1NDM=",
        "number": 1,
        "title": "原型图",
        "user": {
            "login": "slsay",
            "id": 4725762,
            "node_id": "MDQ6VXNlcjQ3MjU3NjI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/4725762?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/slsay",
            "html_url": "https://github.com/slsay",
            "followers_url": "https://api.github.com/users/slsay/followers",
            "following_url": "https://api.github.com/users/slsay/following{/other_user}",
            "gists_url": "https://api.github.com/users/slsay/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/slsay/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/slsay/subscriptions",
            "organizations_url": "https://api.github.com/users/slsay/orgs",
            "repos_url": "https://api.github.com/users/slsay/repos",
            "events_url": "https://api.github.com/users/slsay/events{/privacy}",
            "received_events_url": "https://api.github.com/users/slsay/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1704486567,
                "node_id": "MDU6TGFiZWwxNzA0NDg2NTY3",
                "url": "https://api.github.com/repos/Intern2020OJT/CT_OBJ/labels/%E5%88%86%E7%B1%BB%EF%BC%9A%E8%B5%84%E6%96%99",
                "name": "分类：资料",
                "color": "c5def5",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-11-27T06:19:16Z",
        "updated_at": "2019-11-29T04:23:57Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "body": "[prototype.zip](https://github.com/Intern2020OJT/CT_OBJ/files/3895404/prototype.zip)\r\n"
    }    
]